workflows:
  debug-firebase:
    name: Debug Firebase Distribution
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - firebase_credentials
      vars:
        FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        BUILD_NUMBER: $BUILD_NUMBER
        FLUTTER_VERSION: "3.22.0"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Print version info
        script: |
          echo "Version code: $versionCode"
          echo "Version name: $versionName"
          echo "Build number: $BUILD_NUMBER"

      - name: Build debug APK
        script: |
          flutter build apk \
            --debug \
            --flavor prod \
            --build-number=$BUILD_NUMBER \
            --build-name=$versionName

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/app-prod-debug.apk

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_APP_ID
          groups:
            - testers
          artifact_type: apk
