name: Android Play Store Release Build AAB

on:
  workflow_dispatch:
    inputs:
      tramline-input:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Tramline
        id: tramline
        uses: tramlinehq/deploy-action@v0.1.7
        with:
          input: ${{ github.event.inputs.tramline-input }}

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
          cache: true

      - run: flutter pub get

      - name: Retrieve secrets
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
          KEY_PROPERTIES_B64: ${{ secrets.KEY_PROPERTIES_B64 }}
        run: |
          echo $KEYSTORE_B64 | base64 --decode > android/app/ueno-upload-keystore.jks
          echo $KEY_PROPERTIES_B64 | base64 --decode > android/key.properties

      - run: flutter build appbundle --release --build-number=${{ steps.tramline.outputs.version_code }} --build-name=${{ steps.tramline.outputs.version_name }} --dart-define=BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }} --flavor prod

      - uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab
