name: Android Debug APK (dual=prod+staging)

on:
  workflow_dispatch:
    inputs:
      tramline-input:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Tramline
        id: tramline
        uses: tramlinehq/deploy-action@v0.1.7
        with:
          input: ${{ github.event.inputs.tramline-input }}

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
          cache: true

      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --debug --build-number=${{ github.event.inputs.versionCode }} --build-name=${{ github.event.inputs.versionName }} --flavor prod
      - run: flutter build apk --debug --build-number=${{ github.event.inputs.versionCode }} --build-name=${{ github.event.inputs.versionName }} --flavor staging

      - name: "Upload prod apk to firebase"
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          appId: ${{ vars.FIREBASE_APP_ID }}
          file: build/app/outputs/flutter-apk/app-prod-debug.apk

      - name: "Upload staging apk to firebase"
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          appId: ${{ vars.FIREBASE_STAGING_APP_ID }}
          file: build/app/outputs/flutter-apk/app-staging-debug.apk
