name: iOS Fastlane Release

on:
  workflow_dispatch:
    inputs:
      tramline-input:
        required: false

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Configure Tramline
        id: tramline
        uses: tramlinehq/deploy-action@v0.1.7
        with:
          input: ${{ github.event.inputs.tramline-input }}

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create and setup keychain for CI
        run: |
          security create-keychain -p temp_password fastlane_tmp.keychain
          security set-keychain-settings -t 3600 -u fastlane_tmp.keychain
          security default-keychain -s fastlane_tmp.keychain
          security unlock-keychain -p temp_password fastlane_tmp.keychain

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
          cache: true

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Build the app
        run: |
          flutter build ipa --release --build-number=${{ steps.tramline.outputs.version_code }} --build-name=${{ steps.tramline.outputs.version_name }} --no-codesign --dart-define=BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }}
          ls -la build/ios/archive

      - name: Sign and ship the ipa
        working-directory: ios
        run: |
          bundle install
          bundle exec fastlane match appstore --readonly --verbose
          bundle exec fastlane ios ship_to_testflight
        env:
          ASC_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          ASC_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: fastlane_tmp.keychain
          MATCH_KEYCHAIN_PASSWORD: temp_password
          MATCH_TYPE: appstore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS IPA
          path: build/ios/*.ipa
